// frontend/src/components/LanguageSelector.vue
<template>
  <div class="language-selector">
    <button
      v-for="language in languages"
      :key="language.code"
      :class="['lang-btn', { active: lang === language.code }]"
      @click="setLanguage(language.code)"
      :title="language.name"
      :aria-label="`Switch to ${language.name}`"
    >
      <span class="lang-flag">{{ language.flag }}</span>
      <span class="lang-code">{{ language.code.toUpperCase() }}</span>
    </button>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useLanguageStore } from '../stores/language'

const langStore = useLanguageStore()
const lang = computed(() => langStore.lang)

const languages = [
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'he', name: 'עברית', flag: '🇮🇱' }
]

function setLanguage(code) {
  langStore.setLanguage(code)
}
</script>

<style scoped>
.language-selector {
  position: fixed;
  top: 1.5rem;
  left: 1.5rem;
  display: flex;
  gap: var(--spacing-sm);
  z-index: var(--z-fixed);
}

.lang-btn {
  display: flex;
  align-items: center;
  gap: var(--spacing-xs);
  padding: var(--spacing-sm) var(--spacing-md);
  background: var(--color-card-bg);
  color: var(--color-text);
  border: 2px solid var(--color-border);
  border-radius: var(--radius-lg);
  cursor: pointer;
  font-size: var(--font-size-sm);
  font-weight: 600;
  transition: all var(--transition-fast);
  box-shadow: var(--shadow-sm);
  min-width: 4rem;
}

.lang-btn:hover {
  border-color: var(--color-primary);
  transform: translateY(-2px);
  box-shadow: var(--shadow-md);
}

.lang-btn.active {
  background: var(--color-primary);
  color: #000;
  border-color: var(--color-primary);
  box-shadow: var(--shadow-md);
}

.lang-flag {
  font-size: 1.25rem;
  line-height: 1;
}

.lang-code {
  font-size: var(--font-size-xs);
  letter-spacing: 0.5px;
}

@media (max-width: 640px) {
  .language-selector {
    top: 1rem;
    left: 1rem;
    flex-direction: column;
    gap: var(--spacing-xs);
  }

  .lang-btn {
    min-width: 3rem;
    padding: var(--spacing-sm);
  }

  .lang-code {
    display: none;
  }
}
</style>

// apps/web/src/components/LanguageSelector.tsx
'use client'

interface LanguageSelectorProps {
  lang: string
  setLang: (lang: string) => void
}

export default function LanguageSelector({ lang, setLang }: LanguageSelectorProps) {
  const changeLanguage = (newLang: string) => {
    setLang(newLang)
    document.cookie = `lang=${newLang}; path=/; max-age=31536000` // 1 year
  }

  return (
    <div className="language-selector" style={{
      position: 'fixed',
      top: '1.5rem',
      left: '1.5rem',
      display: 'flex',
      gap: '0.5rem',
      zIndex: 1000
    }}>
      {['de', 'en', 'he'].map((l) => (
        <button
          key={l}
          onClick={() => changeLanguage(l)}
          className={`lang-btn ${lang === l ? 'active' : ''}`}
          style={{
            background: lang === l ? 'var(--accent-color)' : 'var(--card-bg)',
            border: `2px solid ${lang === l ? 'var(--accent-color)' : 'var(--border-color)'}`,
            borderRadius: '0.5rem',
            padding: '0.5rem 0.8rem',
            fontSize: '1.3rem',
            cursor: 'pointer',
            transition: 'all 0.3s',
            textDecoration: 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: '3rem',
            boxShadow: lang === l ? '0 2px 8px rgba(0,184,148,0.4)' : '0 2px 4px rgba(0,0,0,0.1)'
          }}
          title={l === 'de' ? 'Deutsch' : l === 'en' ? 'English' : 'עברית'}
        >
          <i className="fas fa-globe" style={{ marginRight: '0.3rem', fontSize: '0.9rem' }}></i>
          {l.toUpperCase()}
        </button>
      ))}
    </div>
  )
}
